name: GitHub Metrics Single Card
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # 核心属性：走高端极简流
          user: RemotePinee
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Shanghai
          
          # 1. 3D 贡献立方体 (这个是动态的高级感来源)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # 2. 核心战绩展示 (2.9k Stars 及勋章墙)
          plugin_achievements: yes
          plugin_achievements_threshold: A
          plugin_achievements_display: detailed # 详细展示，拉高身价
          
          # 3. 编程语言美化
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          
          # 4. 界面优化 (去掉没用的边框和垃圾信息)
          config_display: columns
